import comp from "D:/dev/doc/my-docs/src/.vuepress/.temp/pages/zh/papm/module.html.vue"
const data = JSON.parse("{\"path\":\"/zh/papm/module.html\",\"title\":\"模块基础结构\",\"lang\":\"zh-CN\",\"frontmatter\":{\"gitInclude\":[],\"description\":\"模块基础结构 模块目录结构 模块存放于 php_module 目录下，每个模块具有唯一的路径，格式如下： 每个模块的初始化文件为 init.php，该文件中需定义一个类，用于处理模块命令。 模块初始化文件（init.php） 模块必须包含一个 init.php 文件，该文件中需要定义以下内容： 模块主类 类名格式为：<Scope><Module>，例如...\",\"head\":[[\"meta\",{\"property\":\"og:url\",\"content\":\"https://vuepress-theme-hope-docs-demo.netlify.app/zh/papm/module.html\"}],[\"meta\",{\"property\":\"og:site_name\",\"content\":\"Docs Demo\"}],[\"meta\",{\"property\":\"og:title\",\"content\":\"模块基础结构\"}],[\"meta\",{\"property\":\"og:description\",\"content\":\"模块基础结构 模块目录结构 模块存放于 php_module 目录下，每个模块具有唯一的路径，格式如下： 每个模块的初始化文件为 init.php，该文件中需定义一个类，用于处理模块命令。 模块初始化文件（init.php） 模块必须包含一个 init.php 文件，该文件中需要定义以下内容： 模块主类 类名格式为：<Scope><Module>，例如...\"}],[\"meta\",{\"property\":\"og:type\",\"content\":\"article\"}],[\"meta\",{\"property\":\"og:locale\",\"content\":\"zh-CN\"}],[\"script\",{\"type\":\"application/ld+json\"},\"{\\\"@context\\\":\\\"https://schema.org\\\",\\\"@type\\\":\\\"Article\\\",\\\"headline\\\":\\\"模块基础结构\\\",\\\"image\\\":[\\\"\\\"],\\\"dateModified\\\":null,\\\"author\\\":[{\\\"@type\\\":\\\"Person\\\",\\\"name\\\":\\\"Mr.Hope\\\",\\\"url\\\":\\\"https://mister-hope.com\\\"}]}\"]]},\"headers\":[{\"level\":2,\"title\":\"模块目录结构\",\"slug\":\"模块目录结构\",\"link\":\"#模块目录结构\",\"children\":[]},{\"level\":2,\"title\":\"模块初始化文件（init.php）\",\"slug\":\"模块初始化文件-init-php\",\"link\":\"#模块初始化文件-init-php\",\"children\":[]},{\"level\":2,\"title\":\"通用要求\",\"slug\":\"通用要求\",\"link\":\"#通用要求\",\"children\":[]},{\"level\":2,\"title\":\"常用功能 API\",\"slug\":\"常用功能-api\",\"link\":\"#常用功能-api\",\"children\":[{\"level\":3,\"title\":\"1. 模块命令执行\",\"slug\":\"_1-模块命令执行\",\"link\":\"#_1-模块命令执行\",\"children\":[]},{\"level\":3,\"title\":\"2. 模块安装流程\",\"slug\":\"_2-模块安装流程\",\"link\":\"#_2-模块安装流程\",\"children\":[]},{\"level\":3,\"title\":\"3. 模块卸载流程\",\"slug\":\"_3-模块卸载流程\",\"link\":\"#_3-模块卸载流程\",\"children\":[]},{\"level\":3,\"title\":\"4. 导出类\",\"slug\":\"_4-导出类\",\"link\":\"#_4-导出类\",\"children\":[]}]},{\"level\":2,\"title\":\"API 接口示例\",\"slug\":\"api-接口示例\",\"link\":\"#api-接口示例\",\"children\":[{\"level\":3,\"title\":\"模块初始化模板\",\"slug\":\"模块初始化模板\",\"link\":\"#模块初始化模板\",\"children\":[]},{\"level\":3,\"title\":\"使用命令调用模块方法\",\"slug\":\"使用命令调用模块方法\",\"link\":\"#使用命令调用模块方法\",\"children\":[]},{\"level\":3,\"title\":\"模块内的 Package 配置文件\",\"slug\":\"模块内的-package-配置文件\",\"link\":\"#模块内的-package-配置文件\",\"children\":[]},{\"level\":3,\"title\":\"项目配置文件\",\"slug\":\"项目配置文件\",\"link\":\"#项目配置文件\",\"children\":[]},{\"level\":3,\"title\":\"常用操作命令\",\"slug\":\"常用操作命令\",\"link\":\"#常用操作命令\",\"children\":[]}]}],\"readingTime\":{\"minutes\":2.93,\"words\":880},\"filePathRelative\":\"zh/papm/module.md\",\"autoDesc\":true}")
export { comp, data }

if (import.meta.webpackHot) {
  import.meta.webpackHot.accept()
  if (__VUE_HMR_RUNTIME__.updatePageData) {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  }
}

if (import.meta.hot) {
  import.meta.hot.accept(({ data }) => {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  })
}
